apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform-ec2
  namespace: flux-system
spec:
  interval: 10m
  path: "./terraform"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-terraform-ec2