apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: ec2
  namespace: terraform
spec:
  hcl: |
    provider "aws" {
      region = 'ap-south-1'
    }
    
    resource "aws_security_group" "ec2_sg" {
      name = "ec2-sg"
      description = "Allow HTTP inbound and all outbound"
      
      ingress {
        from_port   = 80
        to_port     = 80
        protocol    = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
      }
      
      egress {
        from_port   = 0
        to_port     = 0
        protocol    = "-1"
        cidr_blocks = ["0.0.0.0/0"]
      }
    }
    
    resource "aws_instance" "ec2_instance" {
      ami           = "ami-0c55b159cbfafe1f0"
      instance_type = "t3.micro"
      security_groups = [aws_security_group.ec2_sg.name]
      user_data = <<-EOF
                #!/bin/bash
                echo "<h1>Hello from K8s and Flux!</h1>" > /var/www/html/index.html
                nohup python3 -m http.server 80 &
                EOF
    }
  
  writeConnectionSecretToRef:
    name: ec2-connection
    namespace: default
  
  providerRef:
    name: aws-provider